### ISSUE TITLE
High-DPI Scaling Problem

### ISSUE THREAD

**Issue by ITJesse** [mob41/osumer#5] opened 2017-03-14 16:51 UTC
### My environment

- My operating system: Windows 10 Enterprise 1607 14393.693
- My Java Version: Java 1.8.0_121

### About my issue
I have tried ` Disable display scaling on high dpi settings` which take no effect.

![image](https://cloud.githubusercontent.com/assets/3601376/23911474/47fdc934-0920-11e7-9d05-8decb7627c88.png)

**Comment by a1aw** [comment] 2017-03-15 07:40
Err... try turning off scaling in the Windows 10 settings. I think that would be the problem.

Windows Settings -> System -> Display -> Scaling set to 100%

**Comment by ITJesse** [comment] 2017-03-16 05:47
I am sure I have this set to 100%.
My monitor is not HiDPI.

**Comment by a1aw** [comment] 2017-03-16 15:45
What's your screen resolution? I guess the problem is about the screen resolution.

Your screen resolution cannot be smaller than 655x535, which is probably impossible for osu! users to play with.

You can check your screen resolution by:
Windows Settings -> System -> Display -> Advanced display settings -> Resolution

**Comment by a1aw** [comment] 2017-03-16 15:49
If the problem still exists, the another way is to remote your computer, as I don't have more ideas about the problem...
Feel free to contact me at sys.nullptr41@gmail.com

Mine is running Windows 10 Pro, where it should be working as expected.

Edit: ~~Wait. There might be sizing/assigning problems in the UI. I am checking now.~~ No, all fine.

**Comment by mob41** [comment] 2017-03-19 11:29
https://get.teamviewer.com/s25155421

**Comment by ITJesse** [comment] 2017-03-20 13:51
Maybe windows has bug when using non-HiDPI monitor with a HiDPI monitor.
I am very sure I have set the correct DPI for each monitor, but I can not get the osumer display correctly on neither of them.

I have tried remove my second monitor and take no effect.

### Model
Macbook Pro 2016 15inch with touchbar
### Main monitor
15.4", 2,880 × 1,800 (16:10), 220 ppi (15") copy from [wiki](https://zh.wikipedia.org/wiki/MacBook_Pro#.E7.AC.AC.E5.9B.9B.E4.BB.A3_.EF.BC.88Touch_Bar.EF.BC.89)

Set scaling to 175%
### Second monitor
Dell P2317H 1920 x 1080

Set scaling to 100%

**Comment by mob41** [comment] 2017-03-20 14:34
Please join the following TeamViewer session, and keep monitoring your computer movement.

https://get.teamviewer.com/s79290333

**Comment by a1aw** [comment] 2017-03-20 14:46
Or take a look of this: http://stackoverflow.com/questions/36501166/resolution-issue-with-jframe

Seems Java Swing has problems with HiDPI displays. And it (might) be fixed in Java 9

**Comment by a1aw** [comment] 2017-03-20 15:05
The another way is to implement manual Font sizes for all Swing UI components. But it is worth to implement HiDPI functionality into osumer?

But please try these ways first:

1. Set both displays scaling to 100% (I know it will be VERY small in the main monitor). And open osumer and try again

2. Disable the Main Monitor (the MacBook one). Use the second monitor as Main Monitor. Launch osumer and try again.

3. (Probably don't work) Run osumer with Java 9 snapshot

If the above don't work, I "might" try my best to implement manual font size, but that won't be main and important in the development.

**Comment by ITJesse** [comment] 2017-03-22 15:16
1. works
2. works
3. I will try it, not today (

It's maybe the bug of both Windows and Java. 
As the problem has not been solved, please keep this issue open.

**Comment by ITJesse** [comment] 2017-03-22 15:24
I'm sorry but I can't do what you said.
Ehh, for some reason.
I will do my best to help you solve the problem, except remote desktop.
I'm sorry.

mob41 <notifications@github.com>于2017年3月20日周一 下午11:34写道：

**Comment by a1aw** [comment] 2017-03-22 15:27
It's okay😄 I will keep this open and see whether Java will fix HiDPI problems in Java 9.

**Comment by a1aw** [comment] 2020-08-29 14:21
osumer2 now uses JavaFX and seems doesn't have problems in HiDPI environments. Closing this.

**Closed as completed by a1aw** 2020-08-29 14:21 UTC
